### ISSUE TITLE
Can not import strava with Typescript

### ISSUE THREAD

**Issue by nqdai1992** [node-strava/node-strava-v3#129] opened 2022-04-17 15:00 UTC
I think there is a problem with Typescript declaration file

The way that I import the lib
`import { default as strava } from 'strava-v3';`
When I call API
`const activities = await strava.activities.get({ });`
The error that I received
`TypeError: Cannot read properties of undefined (reading 'activities')`

**Comment by markstos** [comment] 2022-04-18 13:52
Patch welcome.

**Comment by edilson** [comment] 2022-04-26 00:23
@nqdai1992 haver you tried without destructuring it? I think that if you want to destructure it's possible to get the activities directly

**Comment by mikehhhhhhh** [comment] 2022-08-05 13:20
I also ran into this issue. As a long term js dev and a new ts dev, the best solution I could find was to switch both js and ts to a named export.

According to the docs, the previous solution should work so I'm not sure why it does not.

**Comment by markstos** [comment] 2023-07-19 20:22
Closing as dupe of #144

**Closed** 2024-02-19 11:55 UTC
Labels: pr-welcome
